### ISSUE TITLE
Outdated code in npm module

### ISSUE THREAD

**Issue by jrmattila** [hupe1980/aws-parameter-cache#1]
Nice library for fetching and caching parameters from SSM, just what I've been looking for!

Could you update the code in NPM registry? There seems to be some outdated code there. I don't know if this is an issue with your build process or what, but the code is a bit different in published module: https://unpkg.com/aws-parameter-cache@1.0.1/lib/ maxAge-parameter is missing and ssmParameter is configured differently.

**Comment by hupe1980** [comment]
@jrmattila You're right! I fixed the issue
