### ISSUE TITLE
Resolve a value from multiple locations - hierarchically

### ISSUE THREAD

**Issue by brettswift** [hupe1980/aws-parameter-cache#8]
I just found this repo, and quite like it.   My use case requires one feature: hierarchical lookups. 

If  I had `/config/app/default/LOG_LEVEL` . and an override if one exists `/config/app/feature-one/LOG_LEVEL`,  I would want to just cache the `LOG_LEVEL` resolved param.   However as written if one of those was null, it would always try to fetch it? 

Is this a complexity you'd find valuable for a contribution?   I may fork - it's fine if you don't want this complexity. 

https://github.com/hupe1980/aws-parameter-cache/blob/master/src/parameter.ts#L54

That line might change from getParameter to GetParameterByPath, and use the recursive lookup. 

How you do hierarchical lookup can be opinionated, so doing it in an open way would be important. 

Feel free to close this of course :) . Or if you see a way this repo would solve my use case with a less impactful change let me know!

**Comment by hupe1980** [comment]
@brettswift  We should definitely support getParameterByPath. 

Maybe:
```javascript
const group = ssmParameterGroup({ path: '/foo' });
const value = group.parameter('/bar').value; // /foo/bar
```

The rest of your use case appears to be very specific and shouldn't be part of such a common library.

**Comment by brettswift** [comment]
Thought that might be the case. It's a pattern I've used repeatedly over the last 5 years so thought it might be more common. 

Thanks
