### ISSUE TITLE
How does caching work for multiple lambdas and lambda calls 

### ISSUE THREAD

**Issue by rekhakuppala** [hupe1980/aws-parameter-cache#9]
Hi Team,

I think this caches param store values within a single lambda call, if we make another lambda call then values are fetched from param store again-is this correct

**Comment by vspdi** [comment]
If you create and wrap a handler class for your tokens and call it outside of the handler methods of your lambda, the underlaying parameters will remain, you may need to refresh the value at some time, use the provided functions for that
